version: '3.7'
services:
  base-go:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined    
    volumes:
      - ..:/workspace:cached
      - ..:/app
    command: /bin/sh -c "while sleep 1000; do :; done"