#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

docker-compose -f $SCRIPT_PATH/../docker-compose.yml \
run --name=composer --rm --no-deps --volume=`pwd`:/app --workdir=/app \
php7 \
composer $@